//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int idDetail { get; set; }
        public Nullable<int> idOrder { get; set; }
        public Nullable<int> idToy { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> subTotal { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Toy Toy { get; set; }
    }
}
