//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Toy()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public int idToy { get; set; }
        public string name { get; set; }
        public Nullable<decimal> price { get; set; }
        public string image { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public string age { get; set; }
        public string country { get; set; }
        public string comment { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public string category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}
